-- Schema utama Sistem Informasi Perpustakaan SMAN 10 Bogor.
-- Dibuat dari pemakaian tabel/kolom di source code aplikasi.
--
-- Jalankan di Supabase SQL Editor untuk database baru, lalu jalankan juga:
--   supabase/sql/checkout_peminjaman.sql
--
-- Catatan:
-- - Script ini memakai nama schema utama saat ini, bukan nama fallback legacy.
-- - App memakai service role dari server, jadi grant minimal diberikan ke service_role.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'status_buku'
  ) then
    create type public.status_buku as enum (
      'tersedia',
      'dipinjam',
      'rusak',
      'dikeluarkan',
      'hilang'
    );
  end if;

  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'status_transaksi'
  ) then
    create type public.status_transaksi as enum (
      'dipinjam',
      'kembali',
      'dikembalikan',
      'terlambat'
    );
  end if;
end
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.admin (
  id_admin integer generated by default as identity primary key,
  nama text not null,
  username text not null,
  email text,
  nomor_telephone text,
  password text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admin_username_lower_key
  on public.admin (lower(username));

create unique index if not exists admin_email_lower_key
  on public.admin (lower(email))
  where email is not null and email <> '';

create table if not exists public.siswa (
  id_siswa integer generated by default as identity primary key,
  nama text not null,
  nis text,
  nisn text not null,
  username text not null,
  email text not null,
  password text,
  kelas text not null,
  tahun_masuk integer not null,
  nomor_whatsapp text not null,
  status_keanggotaan text not null default 'menunggu_verifikasi',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint siswa_status_keanggotaan_check check (
    status_keanggotaan in ('aktif', 'nonaktif', 'menunggu_verifikasi')
  ),
  constraint siswa_tahun_masuk_check check (
    tahun_masuk between 1900 and extract(year from now())::integer + 1
  )
);

create unique index if not exists siswa_nisn_key
  on public.siswa (nisn);

create unique index if not exists siswa_nis_key
  on public.siswa (nis)
  where nis is not null and nis <> '';

create unique index if not exists siswa_username_lower_key
  on public.siswa (lower(username));

create unique index if not exists siswa_email_lower_key
  on public.siswa (lower(email));

create index if not exists siswa_status_keanggotaan_idx
  on public.siswa (status_keanggotaan);

create index if not exists siswa_kelas_idx
  on public.siswa (kelas);

create table if not exists public.buku (
  id_buku integer generated by default as identity primary key,
  judul text not null,
  penulis text not null,
  penerbit text,
  isbn text,
  tahun_terbit integer,
  lokasi_rak text,
  deskripsi_buku text,
  deskripsi text,
  foto_url text,
  stok_buku integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint buku_stok_buku_check check (stok_buku >= 0),
  constraint buku_tahun_terbit_check check (
    tahun_terbit is null
    or tahun_terbit between 1000 and extract(year from now())::integer + 1
  )
);

create unique index if not exists buku_isbn_key
  on public.buku (isbn)
  where isbn is not null and isbn <> '';

create index if not exists buku_judul_idx
  on public.buku (judul);

create index if not exists buku_penulis_idx
  on public.buku (penulis);

create table if not exists public.genre (
  id_genre integer generated by default as identity primary key,
  nama text not null,
  deskripsi text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists genre_nama_lower_key
  on public.genre (lower(nama));

create table if not exists public.buku_genre (
  id_buku integer not null references public.buku(id_buku) on delete cascade,
  id_genre integer not null references public.genre(id_genre) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (id_buku, id_genre)
);

create index if not exists buku_genre_id_genre_idx
  on public.buku_genre (id_genre);

create table if not exists public.copy_buku (
  id_copy_buku integer generated by default as identity primary key,
  id_buku integer not null references public.buku(id_buku) on delete cascade,
  status public.status_buku not null default 'tersedia',
  alasan_dikeluarkan text,
  catatan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists copy_buku_id_buku_status_idx
  on public.copy_buku (id_buku, status);

create index if not exists copy_buku_status_idx
  on public.copy_buku (status);

create table if not exists public.transaksi (
  id_transaksi integer generated by default as identity primary key,
  id_siswa integer not null references public.siswa(id_siswa) on delete restrict,
  id_admin integer not null references public.admin(id_admin) on delete restrict,
  tanggal_pinjam timestamptz not null default now(),
  tanggal_jatuh_tempo timestamptz not null,
  tanggal_kembali timestamptz,
  status public.status_transaksi not null default 'dipinjam',
  catatan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transaksi_tanggal_check check (
    tanggal_jatuh_tempo >= tanggal_pinjam
  )
);

create index if not exists transaksi_id_siswa_idx
  on public.transaksi (id_siswa);

create index if not exists transaksi_id_admin_idx
  on public.transaksi (id_admin);

create index if not exists transaksi_status_idx
  on public.transaksi (status);

create index if not exists transaksi_tanggal_pinjam_idx
  on public.transaksi (tanggal_pinjam);

create index if not exists transaksi_tanggal_jatuh_tempo_idx
  on public.transaksi (tanggal_jatuh_tempo);

create table if not exists public.detail_transaksi (
  id_detail_transaksi integer generated by default as identity primary key,
  id_transaksi integer not null references public.transaksi(id_transaksi) on delete cascade,
  id_copy_buku integer not null references public.copy_buku(id_copy_buku) on delete restrict,
  id_buku integer not null references public.buku(id_buku) on delete restrict,
  jumlah integer not null default 1,
  kondisi_saat_pinjam text not null default 'baik',
  kondisi_saat_kembali text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint detail_transaksi_jumlah_check check (jumlah > 0),
  constraint detail_transaksi_unique_copy_per_transaction unique (
    id_transaksi,
    id_copy_buku
  )
);

create index if not exists detail_transaksi_id_transaksi_idx
  on public.detail_transaksi (id_transaksi);

create index if not exists detail_transaksi_id_buku_idx
  on public.detail_transaksi (id_buku);

create index if not exists detail_transaksi_id_copy_buku_idx
  on public.detail_transaksi (id_copy_buku);

create table if not exists public.absensi (
  id_absensi integer generated by default as identity primary key,
  nama text not null,
  tujuan text,
  jenis_pengunjung text not null,
  waktu_kunjungan timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint absensi_jenis_pengunjung_check check (
    jenis_pengunjung in ('siswa', 'umum')
  )
);

create index if not exists absensi_waktu_kunjungan_idx
  on public.absensi (waktu_kunjungan desc);

create index if not exists absensi_jenis_pengunjung_idx
  on public.absensi (jenis_pengunjung);

create table if not exists public.absensi_siswa (
  id_absensi_siswa integer generated by default as identity primary key,
  id_absensi integer not null references public.absensi(id_absensi) on delete cascade,
  id_siswa integer references public.siswa(id_siswa) on delete set null,
  kelas_saat_absen text,
  tanggal_absensi date not null default ((now() at time zone 'Asia/Jakarta')::date),
  created_at timestamptz not null default now(),
  unique (id_absensi)
);

create unique index if not exists absensi_siswa_once_per_day_key
  on public.absensi_siswa (id_siswa, tanggal_absensi)
  where id_siswa is not null;

create index if not exists absensi_siswa_id_siswa_idx
  on public.absensi_siswa (id_siswa);

create table if not exists public.absensi_umum (
  id_absensi_umum integer generated by default as identity primary key,
  id_absensi integer not null references public.absensi(id_absensi) on delete cascade,
  instansi_asal text not null,
  created_at timestamptz not null default now(),
  unique (id_absensi)
);

create table if not exists public.public_session_settings (
  id integer primary key default 1,
  password_hash text not null,
  updated_by integer references public.admin(id_admin) on delete set null,
  updated_at timestamptz not null default now(),
  constraint public_session_settings_singleton check (id = 1)
);

alter table public.public_session_settings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_admin'
  ) then
    create trigger set_updated_at_admin
    before update on public.admin
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_siswa'
  ) then
    create trigger set_updated_at_siswa
    before update on public.siswa
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_buku'
  ) then
    create trigger set_updated_at_buku
    before update on public.buku
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_genre'
  ) then
    create trigger set_updated_at_genre
    before update on public.genre
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_copy_buku'
  ) then
    create trigger set_updated_at_copy_buku
    before update on public.copy_buku
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_transaksi'
  ) then
    create trigger set_updated_at_transaksi
    before update on public.transaksi
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_detail_transaksi'
  ) then
    create trigger set_updated_at_detail_transaksi
    before update on public.detail_transaksi
    for each row execute function public.set_updated_at();
  end if;

  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_updated_at_absensi'
  ) then
    create trigger set_updated_at_absensi
    before update on public.absensi
    for each row execute function public.set_updated_at();
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'storage'
      and table_name = 'buckets'
  ) then
    insert into storage.buckets (
      id,
      name,
      public,
      file_size_limit,
      allowed_mime_types
    )
    values (
      'foto_buku',
      'foto_buku',
      false,
      10485760,
      array['image/jpeg', 'image/jpg', 'image/png', 'image/webp']::text[]
    )
    on conflict (id) do update
    set
      name = excluded.name,
      public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
  end if;
end
$$;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.admin to service_role;
grant select, insert, update, delete on table public.siswa to service_role;
grant select, insert, update, delete on table public.buku to service_role;
grant select, insert, update, delete on table public.genre to service_role;
grant select, insert, update, delete on table public.buku_genre to service_role;
grant select, insert, update, delete on table public.copy_buku to service_role;
grant select, insert, update, delete on table public.transaksi to service_role;
grant select, insert, update, delete on table public.detail_transaksi to service_role;
grant select, insert, update, delete on table public.absensi to service_role;
grant select, insert, update, delete on table public.absensi_siswa to service_role;
grant select, insert, update, delete on table public.absensi_umum to service_role;
grant select, insert, update, delete on table public.public_session_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Superadmin memakai id_admin = 0 di aplikasi.
-- Buat password bcrypt dulu, lalu sesuaikan contoh seed berikut jika diperlukan:
--
-- insert into public.admin (id_admin, nama, username, email, nomor_telephone, password)
-- values (0, 'Super Admin', 'superadmin', null, null, '$2a$10$...')
-- on conflict (id_admin) do nothing;
